export const CHANGE_MODE = "CHANGE_MODE";

export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const SHOW_USER_CARD = "SHOW_USER_CARD";

export const EDIT_USER_BEGIN = "UPDATE_USER_BEGIN";
export const EDIT_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const EDIT_USER_ERROR = "UPDATE_USER_ERROR";

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_NOTES_BEGIN = "GET_NOTES_BEGIN";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";

export const GET_NOTES_ERROR = "GET_NOTES_ERROR";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
